from common import Q, pre

# Existing questions from the Hugging Face LLM Course end-of-chapter quizzes
# (https://github.com/huggingface/course, Apache License 2.0), translated to
# Vietnamese. Questions with three options or several correct answers were
# adapted to four options with one correct answer; `ref` names the original.

HF = [
# Chapter 1
Q('hf', 'Checkpoint <code>roberta-large-mnli</code> trên Hugging Face Hub thực hiện tác vụ nào?',
  'Phân loại văn bản (suy luận ngôn ngữ tự nhiên: hai câu mâu thuẫn, trung lập hay kéo theo)', ['Tóm tắt văn bản', 'Sinh văn bản', 'Nhận dạng giọng nói'],
  'MNLI là bộ dữ liệu suy luận ngôn ngữ tự nhiên (natural language inference). Mô hình nhận một cặp câu và phân vào ba nhãn contradiction, neutral, entailment, nên đây là bài toán phân loại văn bản.', ref='Chương 1, câu 1'),
Q('hf', 'Đoạn mã sau trả về gì?' + pre('from transformers import pipeline\n\nner = pipeline("ner", aggregation_strategy="simple")\nner("My name is Sylvain and I work at Hugging Face in Brooklyn.")'),
  'Các cụm từ chỉ người, tổ chức hoặc địa điểm trong câu', ['Điểm phân loại câu với nhãn "positive" hoặc "negative"', 'Một đoạn văn bản sinh tiếp câu đã cho', 'Bản dịch của câu sang tiếng Pháp'],
  'Pipeline "ner" (nhận dạng thực thể có tên) gán nhãn PER, ORG, LOC… cho từng token. Với aggregation_strategy="simple", các token cùng một thực thể được gộp lại, ví dụ "Hugging Face" thành một thực thể ORG.', ref='Chương 1, câu 2'),
Q('hf', 'Cần thay "..." bằng chuỗi nào trong đoạn mã sau?' + pre('from transformers import pipeline\n\nfiller = pipeline("fill-mask", model="bert-base-cased")\nresult = filler("...")'),
  '<code>This [MASK] has been waiting for you.</code>', ['<code>This &lt;mask&gt; has been waiting for you.</code>', '<code>This man has been waiting for you.</code>', '<code>This [PAD] has been waiting for you.</code>'],
  'Pipeline fill-mask cần một token che trong câu. Token che của bert-base-cased là [MASK]; &lt;mask&gt; là token che của RoBERTa. Câu không có token che thì không có gì để điền.', ref='Chương 1, câu 3'),
Q('hf', 'Vì sao đoạn mã sau báo lỗi?' + pre('from transformers import pipeline\n\nclassifier = pipeline("zero-shot-classification")\nresult = classifier("This is a course about the Transformers library")'),
  'Pipeline này cần được cung cấp danh sách nhãn để phân loại (candidate_labels)', ['Pipeline này cần nhiều câu chứ không phải một câu', 'Câu đầu vào quá ngắn', 'Pipeline này chỉ hoạt động với tiếng Anh viết hoa'],
  'Zero-shot classification phân loại văn bản vào các nhãn do người dùng đưa ra mà không cần huấn luyện thêm, nên phải truyền candidate_labels=[...]. Pipeline vẫn nhận được một câu đơn lẻ.', ref='Chương 1, câu 4'),
Q('hf', '"Học chuyển giao" (transfer learning) có nghĩa là gì?',
  'Chuyển kiến thức của mô hình pretrained sang mô hình mới bằng cách khởi tạo mô hình mới bằng trọng số của mô hình pretrained', ['Huấn luyện mô hình thứ hai trên đúng bộ dữ liệu của mô hình thứ nhất', 'Xây mô hình thứ hai có cùng kiến trúc với mô hình thứ nhất nhưng khởi tạo ngẫu nhiên', 'Chép dữ liệu huấn luyện của mô hình cũ sang mô hình mới'],
  'Khi mô hình thứ hai được huấn luyện cho tác vụ mới, nó kế thừa kiến thức qua trọng số của mô hình thứ nhất. Chỉ dùng chung kiến trúc thì không chuyển được kiến thức nào.', ref='Chương 1, câu 5'),
Q('hf', 'Phát biểu nào đúng về nhãn dữ liệu khi pretraining mô hình ngôn ngữ?',
  'Thường không cần nhãn do con người gán, vì nhãn được tạo tự động từ chính văn bản (tự giám sát)', ['Bắt buộc mọi câu phải được con người gán nhãn cảm xúc', 'Cần nhãn từ loại cho từng từ', 'Chỉ dùng được dữ liệu đã dịch sang nhiều ngôn ngữ'],
  'Pretraining thường là tự giám sát (self-supervised): mô hình dự đoán từ tiếp theo hoặc điền từ bị che, nên nhãn lấy luôn từ văn bản đầu vào.', ref='Chương 1, câu 6'),
Q('hf', 'Câu nào mô tả đúng nhất ba khái niệm "mô hình" (model), "kiến trúc" (architecture) và "trọng số" (weights)?',
  'Kiến trúc là chuỗi các hàm toán học tạo nên mô hình, còn trọng số là tham số của các hàm đó', ['Nếu mô hình là tòa nhà thì kiến trúc là bản thiết kế, trọng số là người sống trong tòa nhà', 'Kiến trúc là bản đồ để xây mô hình, trọng số là các thành phố trên bản đồ', 'Kiến trúc và trọng số là một'],
  'Cùng một kiến trúc (tập hàm toán học) có thể tạo ra nhiều mô hình khác nhau khi dùng các bộ tham số (trọng số) khác nhau, ví dụ cùng kiến trúc BERT nhưng checkpoint tiếng Anh và tiếng Việt.', ref='Chương 1, câu 7'),
Q('hf', 'Để sinh văn bản hoàn thành một prompt, nên dùng loại mô hình nào?',
  'Mô hình decoder', ['Mô hình encoder', 'Mô hình sequence-to-sequence', 'Mô hình phân cụm K-means'],
  'Mô hình decoder (như GPT) được huấn luyện dự đoán token tiếp theo nên rất hợp với việc sinh tiếp từ một prompt. Encoder tạo biểu diễn cho cả câu, hợp với phân loại. Seq2seq hợp với việc sinh câu dựa trên một câu đầu vào (dịch, tóm tắt).', ref='Chương 1, câu 8'),
Q('hf', 'Để tóm tắt văn bản, nên dùng loại mô hình nào?',
  'Mô hình sequence-to-sequence', ['Mô hình encoder', 'Mô hình decoder', 'Mô hình hồi quy tuyến tính'],
  'Seq2seq (encoder-decoder) đọc toàn bộ văn bản bằng encoder rồi sinh bản tóm tắt bằng decoder. Đây là lựa chọn được khóa học khuyên dùng cho tóm tắt.', ref='Chương 1, câu 9'),
Q('hf', 'Để phân loại văn bản đầu vào theo các nhãn cho trước, nên dùng loại mô hình nào?',
  'Mô hình encoder', ['Mô hình decoder', 'Mô hình sequence-to-sequence', 'Mô hình khuếch tán'],
  'Encoder (như BERT) tạo biểu diễn của toàn bộ câu, có ngữ cảnh hai chiều, rất phù hợp để gắn thêm đầu phân loại.', ref='Chương 1, câu 10'),
Q('hf', 'Thiên lệch (bias) quan sát được ở một mô hình có thể đến từ đâu?',
  ['Mô hình được fine-tune từ một mô hình pretrained và thừa hưởng thiên lệch của nó', 'Dữ liệu huấn luyện bị thiên lệch', 'Chỉ số mà mô hình tối ưu bị thiên lệch', 'Tất cả các nguồn trên'], fix=3,
  exp='Cả ba đều là nguồn thiên lệch. Học chuyển giao giữ lại thiên lệch của mô hình gốc; dữ liệu thiên lệch là nguồn dễ thấy nhất; và mô hình sẽ tối ưu "mù quáng" theo chỉ số được chọn.', ref='Chương 1, câu 11'),

# Chapter 2
Q('hf', 'Thứ tự đúng của pipeline mô hình ngôn ngữ là gì?',
  'Tokenizer chuyển văn bản thành ID, mô hình xử lý ID và đưa ra dự đoán, rồi tokenizer có thể chuyển dự đoán ngược lại thành văn bản', ['Mô hình đọc văn bản trực tiếp và đưa ra dự đoán, tokenizer chuyển dự đoán thành văn bản', 'Tokenizer chuyển văn bản thành ID, mô hình trả về văn bản ngay', 'Mô hình chạy trước, tokenizer chạy song song không phụ thuộc'],
  'Mô hình không hiểu văn bản thô, nó chỉ nhận các ID số. Đầu ra của mô hình cũng là số (logits), nên cần tokenizer giải mã nếu muốn có văn bản.', ref='Chương 2, câu 1'),
Q('hf', 'Tensor đầu ra của mô hình Transformer cơ sở (không có head) có bao nhiêu chiều, và đó là những chiều nào?',
  '3 chiều: batch size, độ dài chuỗi và hidden size', ['2 chiều: độ dài chuỗi và batch size', '2 chiều: độ dài chuỗi và hidden size', '1 chiều: hidden size'],
  'Mô hình luôn xử lý theo batch (kể cả batch 1), mỗi token có một vector ẩn. Ví dụ BERT-base cho shape (batch, seq_len, 768).', ref='Chương 2, câu 2'),
Q('hf', 'Phương pháp nào sau đây KHÔNG phải là tokenization theo từ con (subword)?',
  'Tokenization theo ký tự (character-based)', ['WordPiece', 'BPE', 'Unigram'],
  'WordPiece, BPE và Unigram đều là thuật toán subword. Tokenization theo ký tự tách mọi ký tự riêng, còn tách theo khoảng trắng và dấu câu là tokenization theo từ.', ref='Chương 2, câu 3'),
Q('hf', '"Head" của mô hình (model head) là gì?',
  'Thành phần bổ sung, thường gồm một hoặc vài lớp, chuyển đầu ra của Transformer thành đầu ra theo tác vụ cụ thể', ['Một thành phần trong mạng Transformer cơ sở chuyển tensor tới đúng lớp', 'Tên gọi khác của cơ chế self-attention', 'Lớp embedding đầu tiên của mô hình'],
  'Có nhiều loại head: language modeling head, question answering head, sequence classification head… Cùng một thân Transformer có thể gắn các head khác nhau. Self-attention có "attention heads" nhưng đó là khái niệm khác.', ref='Chương 2, câu 4'),
Q('hf', '<code>AutoModel</code> là gì?',
  'Đối tượng tự trả về đúng kiến trúc dựa trên checkpoint được chỉ định', ['Mô hình tự động huấn luyện trên dữ liệu của bạn', 'Mô hình tự phát hiện ngôn ngữ đầu vào để tải trọng số phù hợp', 'Mô hình tự chọn siêu tham số tốt nhất'],
  'AutoModel.from_pretrained(checkpoint) đọc file cấu hình của checkpoint để biết kiến trúc (BERT, GPT-2…) rồi tạo đúng lớp mô hình. Huấn luyện tự động là sản phẩm AutoTrain, không phải AutoModel.', ref='Chương 2, câu 5'),
Q('hf', 'Khi gộp các chuỗi có độ dài khác nhau vào cùng một batch, cần lưu ý những kỹ thuật nào?',
  ['Cắt bớt (truncation)', 'Đệm (padding)', 'Mặt nạ attention (attention mask)', 'Cả ba kỹ thuật trên'], fix=3,
  exp='Truncation và padding đưa các chuỗi về cùng độ dài để tạo tensor hình chữ nhật. Attention mask báo cho mô hình bỏ qua token đệm, nếu không kết quả sẽ bị sai lệch.', ref='Chương 2, câu 6'),
Q('hf', 'Áp dụng softmax lên logits của mô hình phân loại chuỗi nhằm mục đích gì?',
  'Đưa các giá trị về khoảng [0, 1] với tổng bằng 1, để có thể hiểu như xác suất', ['Làm logits "mềm" hơn để kết quả đáng tin hơn', 'Giảm số chiều của logits', 'Loại bỏ lớp có logit âm'],
  'Logits có thể là số bất kỳ. Softmax chặn giá trị trong [0, 1] và chuẩn hóa tổng bằng 1, nhờ đó diễn giải được như phân phối xác suất. Nó không làm dự đoán đáng tin hơn.', ref='Chương 2, câu 7'),
Q('hf', 'Biến <code>result</code> trong đoạn mã sau chứa gì?' + pre('from transformers import AutoTokenizer\n\ntokenizer = AutoTokenizer.from_pretrained("bert-base-cased")\nresult = tokenizer.tokenize("Hello!")'),
  'Danh sách các chuỗi, mỗi chuỗi là một token', ['Danh sách các ID', 'Một chuỗi chứa tất cả token nối lại', 'Một tensor PyTorch'],
  'tokenize() chỉ tách văn bản thành token dạng chuỗi, ví dụ ["Hello", "!"]. Muốn có ID cần gọi convert_tokens_to_ids() hoặc gọi trực tiếp tokenizer(...).', ref='Chương 2, câu 9'),
Q('hf', 'Đoạn mã sau có vấn đề gì?' + pre('from transformers import AutoTokenizer, AutoModel\n\ntokenizer = AutoTokenizer.from_pretrained("bert-base-cased")\nmodel = AutoModel.from_pretrained("gpt2")\n\nencoded = tokenizer("Hey!", return_tensors="pt")\nresult = model(**encoded)'),
  'Tokenizer và mô hình phải đến từ cùng một checkpoint', ['Không có vấn đề gì', 'Phải padding và truncation vì mọi đầu vào là batch', 'Phải dùng return_tensors="np" thay cho "pt"'],
  'Tokenizer của BERT sinh ID theo từ vựng của BERT, còn GPT-2 có từ vựng khác. Mô hình nhận ID trỏ sai token nên kết quả vô nghĩa. Với một câu duy nhất thì padding hay truncation không cần thiết.', ref='Chương 2, câu 10'),

# Chapter 3
Q('hf', 'Vì sao nên dùng padding động (dynamic padding) thay vì đệm mọi chuỗi tới độ dài tối đa của cả bộ dữ liệu?',
  'Giảm tính toán thừa vì chỉ đệm tới độ dài lớn nhất trong từng batch', ['Vì kiến trúc mô hình bắt buộc padding động', 'Vì padding động làm tăng độ chính xác', 'Vì DataCollatorWithPadding không hỗ trợ padding cố định'],
  'Đệm tới độ dài dài nhất của cả bộ dữ liệu làm hầu hết batch chứa rất nhiều token đệm vô ích. Padding động (ví dụ với DataCollatorWithPadding) chỉ đệm tới câu dài nhất trong batch. Chiến lược padding không trực tiếp ảnh hưởng độ chính xác.', ref='Chương 3, mục 2, câu 2'),
Q('hf', 'Trường <code>token_type_ids</code> trong đầu ra tokenizer của BERT biểu diễn điều gì?',
  'Mỗi token thuộc câu nào khi xử lý cặp câu', ['Vị trí của từng token trong chuỗi', 'Mặt nạ attention của từng token', 'ID trong từ vựng của từng token'],
  'token_type_ids bằng 0 cho câu thứ nhất và 1 cho câu thứ hai. Vị trí do position embeddings đảm nhận, attention_mask là trường riêng, còn ID từ vựng là input_ids.', ref='Chương 3, mục 2, câu 3'),
Q('hf', 'Đặt <code>fp16=True</code> trong <code>TrainingArguments</code> có tác dụng gì?',
  'Huấn luyện mixed precision với số thực dấu phẩy động 16-bit, nhanh hơn và tốn ít bộ nhớ hơn', ['Dùng số nguyên 16-bit', 'Huấn luyện đúng 16 epoch', 'Dùng 16 GPU để huấn luyện phân tán'],
  'Mixed precision tính phần lớn phép toán bằng float16 và giữ một bản trọng số float32 để cập nhật ổn định, nhờ đó tăng tốc trên GPU hỗ trợ và giảm bộ nhớ.', ref='Chương 3, mục 3, câu 3'),
Q('hf', 'Tích lũy gradient (gradient accumulation) là gì và bật thế nào trong Trainer?',
  'Cộng dồn gradient qua nhiều batch rồi mới cập nhật trọng số, bật bằng <code>gradient_accumulation_steps</code>', ['Lưu gradient xuống đĩa, bật bằng <code>save_gradients=True</code>', 'Tăng tốc tính gradient, tự bật khi dùng fp16', 'Chống tràn gradient, bật bằng <code>gradient_clipping=True</code>'],
  'Tích lũy gradient mô phỏng batch lớn khi bộ nhớ chỉ đủ cho batch nhỏ. Ví dụ batch 8 với gradient_accumulation_steps=4 tương đương batch hiệu dụng 32. Chống tràn gradient là gradient clipping, một kỹ thuật khác.', ref='Chương 3, mục 3, câu 6'),
Q('hf', 'Khác biệt chính giữa bộ tối ưu Adam và AdamW là gì?',
  'AdamW tách riêng weight decay khỏi bước cập nhật dựa trên gradient (decoupled weight decay)', ['AdamW dùng lịch learning rate khác', 'AdamW chỉ dùng được cho Transformer', 'AdamW tốn ít bộ nhớ hơn Adam'],
  'Trong Adam, chính quy hóa L2 được cộng vào gradient rồi bị chia cho căn bậc hai của moment bậc hai, nên tác dụng không đều. AdamW trừ weight decay trực tiếp vào trọng số, cho chính quy hóa tốt hơn. Bộ nhớ hai thuật toán gần như nhau.', ref='Chương 3, mục 4, câu 1'),
Q('hf', 'Trong một vòng lặp huấn luyện, thứ tự thao tác nào đúng?',
  'Forward → backward → optimizer step → scheduler step → xóa gradient', ['Forward → xóa gradient → backward → optimizer step', 'Xóa gradient → forward → optimizer step → backward', 'Backward → forward → optimizer step → xóa gradient'],
  'Tính mất mát (forward), tính gradient (backward), cập nhật tham số (optimizer.step), cập nhật learning rate (scheduler.step), rồi xóa gradient (zero_grad) để không cộng dồn sang bước sau. Xóa gradient giữa forward và backward sẽ không xóa gì cả, còn đặt trước optimizer.step thì làm mất gradient vừa tính.', ref='Chương 3, mục 4, câu 2'),
Q('hf', 'Gọi <code>model.eval()</code> trước khi đánh giá có tác dụng gì?',
  'Thay đổi hành vi của các lớp như dropout và batch normalization sang chế độ suy luận', ['Đóng băng tham số để không thể cập nhật', 'Bật tính gradient cho các chỉ số đánh giá', 'Tự động tính các chỉ số đánh giá'],
  'Ở chế độ eval, dropout bị tắt và batch norm dùng thống kê tích lũy thay cho thống kê của batch hiện tại. Đóng băng tham số là đặt requires_grad=False; muốn tắt gradient khi đánh giá thì dùng torch.no_grad().', ref='Chương 3, mục 4, câu 5'),
Q('hf', 'Mục đích của <code>torch.no_grad()</code> khi đánh giá là gì?',
  'Tiết kiệm bộ nhớ và tăng tốc nhờ tắt việc theo dõi gradient', ['Ngăn mô hình đưa ra dự đoán', 'Bật chế độ đánh giá cho mô hình', 'Đảm bảo kết quả giống nhau giữa các lần chạy'],
  'Khi đánh giá không cần gradient, nên không cần lưu đồ thị tính toán. Chế độ đánh giá do model.eval() bật; tính tái lập kết quả do đặt seed.', ref='Chương 3, mục 4, câu 6'),
Q('hf', 'Vì sao đường cong accuracy thường có dạng "bậc thang" thay vì tăng mượt như đường mất mát?',
  'Accuracy là chỉ số rời rạc, chỉ thay đổi khi dự đoán vượt qua ngưỡng quyết định', ['Có lỗi trong cách tính accuracy', 'Mô hình không học hiệu quả', 'Batch size quá nhỏ'],
  'Mất mát thay đổi liên tục theo độ tự tin của mô hình. Accuracy chỉ đếm đúng/sai, nên mô hình tự tin hơn một chút mà chưa đổi dự đoán thì accuracy không đổi. Dạng bậc thang là bình thường.', ref='Chương 3, mục 5, câu 2'),
Q('hf', 'Khi đường cong học dao động thất thường, mạnh, cách xử lý hợp lý nhất là gì?',
  'Giảm learning rate và có thể tăng batch size', ['Tăng learning rate để hội tụ nhanh hơn', 'Dừng huấn luyện ngay vì mô hình sẽ không cải thiện', 'Chuyển sang kiến trúc hoàn toàn khác'],
  'Learning rate thấp hơn cho bước cập nhật nhỏ hơn; batch lớn hơn cho gradient ít nhiễu hơn. Cả hai làm quá trình huấn luyện ổn định. Tăng learning rate sẽ làm dao động mạnh hơn.', ref='Chương 3, mục 5, câu 3'),
Q('hf', 'Dấu hiệu nào cho thấy mô hình có thể đang underfitting?',
  'Hiệu suất trên cả tập huấn luyện và tập validation đều kém và sớm chững lại', ['Accuracy huấn luyện cao hơn nhiều so với validation', 'Đường cong học rất mượt, không dao động', 'Mất mát validation giảm nhanh hơn mất mát huấn luyện'],
  'Underfitting xảy ra khi mô hình không đủ năng lực học quy luật nên kém trên cả hai tập. Train tốt mà validation kém là overfitting.', ref='Chương 3, mục 5, câu 5'),

# Chapter 6
Q('hf', 'Khi nào nên huấn luyện một tokenizer mới?',
  'Khi dữ liệu khác với dữ liệu của mô hình pretrained hiện có và bạn muốn pretrain một mô hình mới', ['Khi dữ liệu giống dữ liệu của mô hình pretrained và bạn muốn pretrain mô hình mới', 'Khi dữ liệu giống dữ liệu của mô hình pretrained và bạn muốn fine-tune mô hình đó', 'Khi dữ liệu khác dữ liệu của mô hình pretrained nhưng bạn muốn fine-tune mô hình pretrained đó'],
  'Fine-tune một mô hình pretrained luôn phải dùng đúng tokenizer của nó. Khi pretrain mô hình mới trên dữ liệu giống dữ liệu cũ thì dùng lại tokenizer cũ là đủ. Chỉ khi pretrain trên miền dữ liệu khác (ngôn ngữ khác, mã nguồn…) thì tokenizer mới mới có lợi.', ref='Chương 6, câu 1'),
Q('hf', 'Pipeline <code>question-answering</code> xử lý ngữ cảnh dài thế nào?',
  'Chia ngữ cảnh thành nhiều đoạn có phần chồng lấn, rồi chọn câu trả lời có điểm cao nhất trong các đoạn', ['Cắt bỏ phần vượt quá độ dài tối đa của mô hình', 'Chia thành nhiều đoạn rồi lấy trung bình kết quả', 'Chia thành nhiều đoạn không chồng lấn để tiết kiệm tính toán'],
  'Lấy trung bình không hợp lý vì nhiều đoạn không chứa câu trả lời. Phần chồng lấn tránh trường hợp câu trả lời bị cắt đôi ở ranh giới hai đoạn.', ref='Chương 6, câu 5'),
Q('hf', 'Trong pipeline của tokenizer, bước "chuẩn hóa" (normalization) là gì?',
  'Các bước làm sạch văn bản ở giai đoạn đầu, như bỏ dấu, bỏ khoảng trắng thừa, chuyển chữ thường', ['Kỹ thuật tăng cường dữ liệu bằng cách bỏ từ hiếm', 'Bước hậu xử lý thêm các token đặc biệt', 'Đưa embedding về trung bình 0 và độ lệch chuẩn 1'],
  'Normalization là bước đầu tiên của tokenizer. Thêm token đặc biệt là bước post-processing. Đưa giá trị về trung bình 0, độ lệch chuẩn 1 là nghĩa của "chuẩn hóa" trong thị giác máy tính, không phải trong tokenizer.', ref='Chương 6, câu 6'),
Q('hf', 'Phát biểu nào đúng về thuật toán tokenization BPE?',
  'Bắt đầu với từ vựng nhỏ và học các quy tắc gộp, mỗi lần gộp cặp token xuất hiện thường xuyên nhất', ['Bắt đầu với từ vựng lớn rồi loại dần token', 'Gộp cặp token tối đa hóa điểm số ưu tiên cặp phổ biến gồm các phần ít phổ biến', 'Tách từ bằng cách tìm từ con dài nhất từ đầu từ có trong từ vựng'],
  'BPE gộp theo tần suất. Khi mã hóa, nó tách từ thành ký tự rồi áp lần lượt các quy tắc gộp đã học. Loại dần token từ từ vựng lớn là cách của Unigram; dùng điểm số và tìm từ con dài nhất là cách của WordPiece.', ref='Chương 6, câu 8'),
Q('hf', 'Phát biểu nào đúng về thuật toán tokenization WordPiece?',
  'Khi mã hóa, tìm từ con dài nhất từ đầu từ có trong từ vựng rồi lặp lại với phần còn lại', ['Bắt đầu với từ vựng lớn rồi loại dần token', 'Gộp cặp token xuất hiện thường xuyên nhất', 'Tìm cách tách có xác suất cao nhất theo mô hình'],
  'WordPiece học quy tắc gộp theo điểm số ưu tiên cặp phổ biến nhưng gồm các phần riêng lẻ ít phổ biến, và mã hóa theo kiểu tìm từ con dài nhất. Gộp theo tần suất là BPE; tìm cách tách xác suất cao nhất là Unigram.', ref='Chương 6, câu 9'),
Q('hf', 'Phát biểu nào đúng về thuật toán tokenization Unigram?',
  'Bắt đầu với từ vựng lớn và loại dần token sao cho mất mát trên toàn bộ corpus tăng ít nhất', ['Bắt đầu với từ vựng nhỏ và học quy tắc gộp', 'Giữ lại các từ con xuất hiện nhiều nhất', 'Tách từ thành ký tự rồi áp quy tắc gộp'],
  'Unigram điều chỉnh từ vựng bằng cách tối thiểu hóa mất mát tính trên toàn corpus. Khi mã hóa, nó chọn cách tách có xác suất cao nhất theo mô hình. Học quy tắc gộp từ từ vựng nhỏ là cách của BPE và WordPiece.', ref='Chương 6, câu 10'),

# Chapter 7
Q('hf', 'Vấn đề gì nảy sinh khi tokenize các từ trong bài toán phân loại token (token classification) và muốn gán nhãn cho token?',
  'Một từ có thể sinh ra nhiều token nên số token nhiều hơn số nhãn, cần căn chỉnh nhãn với token', ['Tokenizer thêm token đặc biệt mà không có cách nào xử lý', 'Token thêm vào không có nhãn nên không có vấn đề gì', 'Tokenizer làm mất toàn bộ dấu câu'],
  'Nhãn ban đầu gán theo từ. Sau khi tách subword, một từ như "Brooklyn" có thể thành nhiều token, nên phải căn chỉnh lại. Token đặc biệt được gán nhãn −100 để bị bỏ qua khi tính mất mát.', ref='Chương 7, câu 3'),
Q('hf', 'Trong bài toán masked language modeling, nhãn (labels) là gì?',
  'Một số token đầu vào bị che ngẫu nhiên, và nhãn là các token gốc của đầu vào', ['Một số token bị che, nhãn là token gốc dịch sang trái một vị trí', 'Một số token bị che, nhãn là câu tích cực hay tiêu cực', 'Một số token trong hai câu bị che, nhãn là hai câu có giống nhau không'],
  'Mô hình phải khôi phục token gốc ở các vị trí bị che. Dịch nhãn sang trái một vị trí ứng với dự đoán từ tiếp theo (causal language modeling). Hai phương án còn lại là phân loại chuỗi.', ref='Chương 7, câu 5'),
Q('hf', 'Vì sao pretrain mô hình ngôn ngữ trên lượng văn bản khổng lồ lại dễ thực hiện?',
  'Vì mục tiêu pretraining không cần con người gán nhãn dữ liệu', ['Vì trên internet có rất nhiều văn bản', 'Vì thư viện Transformers chỉ cần vài dòng code', 'Vì mô hình ngôn ngữ không cần hàm mất mát'],
  'Mô hình hóa ngôn ngữ là bài toán tự giám sát, nhãn lấy từ chính văn bản, nên mở rộng quy mô dữ liệu không tốn công gán nhãn. Internet có nhiều văn bản là đúng, nhưng nếu phải gán nhãn tay thì vẫn không thể dùng hết.', ref='Chương 7, câu 11'),

# Chapter 8
Q('hf', 'Cách tốt nhất để gỡ lỗi một lỗi CUDA khó hiểu là gì?',
  'Chạy lại cùng đoạn mã trên CPU để nhận thông báo lỗi rõ ràng hơn', ['Đăng thông báo lỗi lên diễn đàn', 'Đọc traceback để tìm nơi gây lỗi', 'Khởi động lại kernel Jupyter'],
  'Phần lớn thao tác CUDA chạy bất đồng bộ nên lỗi thường không được báo tại đúng dòng gây ra, và thông báo lỗi CUDA rất ít thông tin. Trên CPU, lỗi (ví dụ chỉ số nhãn vượt số lớp) được báo rõ tại đúng chỗ. Giảm batch size chỉ hữu ích với lỗi hết bộ nhớ.', ref='Chương 8, câu 5'),
Q('hf', 'Vì sao cho mô hình overfit một batch thường là kỹ thuật gỡ lỗi tốt?',
  'Nó kiểm tra nhanh mô hình có khả năng đưa mất mát về gần 0 hay không', ['Không phải kỹ thuật tốt, vì overfitting luôn xấu', 'Nó kiểm tra shape của đầu vào và nhãn có đúng không', 'Nó làm mô hình tổng quát hóa tốt hơn'],
  'Với một batch nhỏ (chỉ vài mẫu), mô hình cài đặt đúng phải học thuộc được. Nếu mất mát không giảm thì có lỗi trong dữ liệu, hàm mất mát hay vòng lặp huấn luyện. Shape sai thì đã không chạy được ngay từ đầu.', ref='Chương 8, câu 7'),

# Chapter 11, 12
Q('hf', 'Benchmark nào đánh giá kiến thức của mô hình ngôn ngữ trên 57 lĩnh vực khác nhau?',
  'MMLU', ['GSM8K', 'BBH (Big Bench Hard)', 'ImageNet'],
  'MMLU (Massive Multitask Language Understanding) gồm câu hỏi trắc nghiệm ở 57 lĩnh vực, từ khoa học tới nhân văn. GSM8K tập trung vào toán tiểu học có lời văn, BBH tập trung vào các tác vụ suy luận khó.', ref='Chương 11, mục 5, câu 2'),
Q('hf', 'Lợi ích chính của RLHF (học tăng cường từ phản hồi của con người) khi huấn luyện mô hình ngôn ngữ là gì?',
  'Giúp mô hình phù hợp hơn với sở thích và giá trị của con người', ['Giúp mô hình sinh văn bản nhanh hơn', 'Giảm bộ nhớ mô hình sử dụng', 'Thay thế hoàn toàn giai đoạn pretraining'],
  'RLHF dùng phản hồi của con người (thường qua một reward model học từ các so sánh) để hướng mô hình tới câu trả lời hữu ích, vô hại và trung thực hơn. Nó không nhằm cải thiện tốc độ hay bộ nhớ.', ref='Chương 12, mục 2, câu 2'),
]
