from common import Q, table, frac, pre

# Câu soạn mới theo nội dung các nguồn trong SOURCES. Mỗi đề chọn một phần theo chỉ số.

QS = [
# --- Huấn luyện mạng nơ-ron (deeplearning.ai – Improving DNN, CS231n) ---
Q('dlai-improve', 'Một mô hình nhận dạng ảnh có sai số huấn luyện 1% và sai số trên tập dev 11%, trong khi sai số của con người gần 0%. Vấn đề chính của mô hình là gì?',
  'Phương sai cao (high variance)', ['Độ lệch cao (high bias)', 'Cả độ lệch và phương sai đều thấp', 'Tập dev bị gán nhãn sai hoàn toàn'],
  'Sai số huấn luyện thấp (1%) nhưng sai số dev cao hơn nhiều (11%) cho thấy mô hình khớp tốt dữ liệu huấn luyện mà không tổng quát hóa được, tức là phương sai cao. Hướng xử lý: thêm dữ liệu, chính quy hóa, dropout.'),
Q('dlai-improve', 'Sai số huấn luyện là 15%, sai số dev là 16%, còn sai số Bayes ước lượng khoảng 0.5%. Hành động nào nên ưu tiên?',
  'Dùng mạng lớn hơn hoặc huấn luyện lâu hơn', ['Thu thập thêm dữ liệu huấn luyện', 'Tăng hệ số chính quy hóa L2', 'Tăng tỉ lệ dropout'],
  'Khoảng cách tới sai số Bayes (15% so với 0.5%) rất lớn, trong khi khoảng cách train–dev chỉ 1%. Đây là độ lệch cao (underfitting), nên cần tăng năng lực mô hình hoặc huấn luyện lâu hơn. Thêm dữ liệu hay tăng chính quy hóa chỉ giúp giảm phương sai.'),
Q('dlai-improve', 'Trong kỹ thuật "inverted dropout" với xác suất giữ lại keep_prob, vì sao các activation được chia cho keep_prob khi huấn luyện?',
  'Để giữ nguyên giá trị kỳ vọng của activation, nhờ đó không phải điều chỉnh gì khi suy luận', ['Để tăng tốc độ tính toán trên GPU', 'Để giảm số tham số của mạng', 'Để các nơ-ron bị tắt có gradient bằng 0'],
  'Khi tắt ngẫu nhiên một phần nơ-ron, tổng activation giảm đi theo tỉ lệ keep_prob. Chia cho keep_prob bù lại phần này nên kỳ vọng không đổi. Nhờ vậy lúc suy luận chỉ cần tắt dropout, không phải nhân thêm hệ số.'),
Q('dlai-improve', 'Khi đánh giá mô hình đã huấn luyện có dropout trên tập test, ta nên làm gì?',
  'Không áp dụng dropout, dùng toàn bộ nơ-ron', ['Vẫn áp dụng dropout với cùng keep_prob', 'Áp dụng dropout và lấy kết quả của một lần chạy duy nhất', 'Nhân mọi trọng số với keep_prob rồi mới áp dụng dropout'],
  'Dropout chỉ là kỹ thuật chính quy hóa lúc huấn luyện. Khi suy luận ta dùng toàn bộ mạng để kết quả ổn định và có tính tất định; với inverted dropout không cần chỉnh thêm hệ số nào. Trong PyTorch, gọi model.eval() sẽ tự tắt dropout.'),
Q('dlai-improve', 'Vì sao chính quy hóa L2 còn được gọi là "weight decay"?',
  'Vì mỗi bước cập nhật nhân trọng số với một hệ số nhỏ hơn 1 trước khi trừ gradient', ['Vì trọng số giảm dần về 0 sau mỗi epoch bất kể gradient', 'Vì learning rate giảm dần theo thời gian', 'Vì nó loại bỏ hẳn các trọng số nhỏ khỏi mạng'],
  'Với hàm mất mát có thêm (λ/2m)‖w‖², bước cập nhật là w ← (1 − αλ/m)·w − α·∂J/∂w. Hệ số (1 − αλ/m) &lt; 1 làm trọng số "co lại" một chút ở mỗi bước, nên gọi là weight decay.'),
Q('dlai-improve', 'Khi tăng hệ số chính quy hóa λ của L2, điều gì thường xảy ra?',
  'Trọng số nhỏ lại, phương sai giảm nhưng độ lệch có thể tăng', ['Trọng số lớn hơn, mô hình phức tạp hơn', 'Sai số huấn luyện luôn giảm', 'Mô hình không còn bị ảnh hưởng bởi learning rate'],
  'λ lớn phạt mạnh trọng số lớn, buộc mô hình đơn giản hơn. Điều này giảm overfitting (phương sai) nhưng nếu λ quá lớn mô hình sẽ underfit, tức độ lệch tăng.'),
Q('dlai-improve', 'Lợi ích chính của việc chuẩn hóa đầu vào (trừ trung bình, chia độ lệch chuẩn) khi huấn luyện mạng nơ-ron là gì?',
  'Mặt hàm mất mát cân đối hơn nên có thể dùng learning rate lớn hơn và hội tụ nhanh hơn', ['Giảm số lớp ẩn cần thiết', 'Tự động loại bỏ ngoại lệ', 'Thay thế được chính quy hóa'],
  'Khi các đặc trưng có thang đo rất khác nhau, đường đồng mức của hàm mất mát bị kéo dài, gradient descent phải đi zíc zắc với bước nhỏ. Chuẩn hóa làm đường đồng mức tròn hơn nên tối ưu nhanh và ổn định hơn.'),
Q('dlai-improve', 'Khi đã chuẩn hóa dữ liệu huấn luyện bằng trung bình μ và độ lệch chuẩn σ, dữ liệu test nên được chuẩn hóa thế nào?',
  'Dùng đúng μ và σ đã tính trên tập huấn luyện', ['Tính μ và σ riêng trên tập test', 'Không cần chuẩn hóa tập test', 'Dùng μ và σ của toàn bộ dữ liệu train và test gộp lại'],
  'Train và test phải đi qua cùng một phép biến đổi thì mô hình mới nhìn thấy cùng một phân phối đầu vào. Tính thống kê trên tập test, hay gộp test vào, là rò rỉ dữ liệu và làm sai lệch đánh giá.'),
Q('dlai-improve', 'Với lớp dùng hàm kích hoạt ReLU, cách khởi tạo trọng số He chọn phương sai của trọng số bằng bao nhiêu (n là số đầu vào của lớp)?',
  '2 / n', ['1 / n', '1 / (2n)', 'n / 2'],
  'He initialization dùng Var(w) = 2/n, phù hợp với ReLU vì ReLU triệt tiêu khoảng một nửa tín hiệu. Xavier dùng 1/n (hoặc 2/(n_in + n_out)) cho tanh/sigmoid. Mục tiêu là giữ phương sai activation ổn định qua các lớp, tránh gradient biến mất hoặc bùng nổ.'),
Q('dlai-improve', 'Phát biểu nào đúng về kiểm tra gradient (gradient checking)?',
  'Chỉ dùng khi gỡ lỗi, không bật trong lúc huấn luyện, và nên tắt dropout khi kiểm tra', ['Nên chạy ở mọi bước huấn luyện để đảm bảo gradient đúng', 'Dùng sai phân một phía f(θ+ε) − f(θ) cho kết quả chính xác hơn sai phân hai phía', 'Hoạt động tốt kể cả khi đang bật dropout'],
  'Gradient checking so sánh gradient từ backprop với xấp xỉ số [J(θ+ε) − J(θ−ε)] / 2ε. Phép này rất chậm nên chỉ dùng để gỡ lỗi. Dropout làm hàm mất mát thay đổi ngẫu nhiên nên phải tắt khi kiểm tra. Sai phân hai phía chính xác hơn sai phân một phía.'),
Q('dlai-improve', 'Trong gradient descent với momentum, nếu β = 0.9 thì trung bình trượt mũ (exponentially weighted average) xấp xỉ lấy trung bình của khoảng bao nhiêu gradient gần nhất?',
  '10', ['9', '90', '100'],
  'Trung bình trượt mũ với hệ số β xấp xỉ trung bình của 1/(1 − β) giá trị gần nhất. Với β = 0.9 thì 1/0.1 = 10 bước.'),
Q('dlai-improve', 'Trung bình trượt mũ được tính theo v<sub>t</sub> = β·v<sub>t−1</sub> + (1 − β)·θ<sub>t</sub> với v<sub>0</sub> = 0, β = 0.9. Nếu θ<sub>1</sub> = 10 thì giá trị sau hiệu chỉnh độ lệch (bias correction) v<sub>1</sub>/(1 − β<sup>1</sup>) bằng bao nhiêu?',
  ['1', '9', '10', '0.1'], fix=2,
  exp='v<sub>1</sub> = 0.9·0 + 0.1·10 = 1. Do khởi tạo bằng 0 nên giá trị bị kéo về 0 ở các bước đầu. Hiệu chỉnh: 1 / (1 − 0.9) = 10, đúng bằng θ<sub>1</sub>.'),
Q('dlai-improve', 'Bộ giá trị mặc định thường dùng cho các siêu tham số của Adam là gì?',
  'β<sub>1</sub> = 0.9, β<sub>2</sub> = 0.999, ε = 10<sup>−8</sup>', ['β<sub>1</sub> = 0.999, β<sub>2</sub> = 0.9, ε = 10<sup>−8</sup>', 'β<sub>1</sub> = 0.5, β<sub>2</sub> = 0.5, ε = 0.1', 'β<sub>1</sub> = 0.9, β<sub>2</sub> = 0.9, ε = 1'],
  'Adam kết hợp momentum (β<sub>1</sub> = 0.9 cho trung bình gradient) và RMSProp (β<sub>2</sub> = 0.999 cho trung bình bình phương gradient). ε rất nhỏ để tránh chia cho 0. Thường chỉ cần tinh chỉnh learning rate.'),
Q('dlai-improve', 'Learning rate được giảm theo công thức α = α<sub>0</sub> / (1 + decay_rate × epoch). Với α<sub>0</sub> = 0.2 và decay_rate = 1, learning rate ở epoch 3 là bao nhiêu?',
  ['0.1', '0.0667', '0.05', '0.04'], fix=2,
  exp='α = 0.2 / (1 + 1 × 3) = 0.2 / 4 = 0.05.'),
Q('dlai-improve', 'Khi tìm siêu tham số cho mạng nơ-ron, cách nào thường hiệu quả hơn tìm kiếm theo lưới (grid search)?',
  'Lấy mẫu ngẫu nhiên các tổ hợp siêu tham số (random search)', ['Thử lần lượt từng giá trị cách đều nhau của mọi siêu tham số', 'Chỉ tinh chỉnh số epoch', 'Cố định tất cả và chỉ đổi seed ngẫu nhiên'],
  'Không phải siêu tham số nào cũng quan trọng như nhau. Với random search, mỗi lần thử cho một giá trị mới của từng siêu tham số, nên khám phá được nhiều giá trị khác nhau của siêu tham số quan trọng hơn so với lưới cùng số lần thử.'),
Q('dlai-improve', 'Muốn lấy mẫu learning rate α trong khoảng [10<sup>−4</sup>, 1] cho hợp lý, nên làm thế nào?',
  'Lấy r ngẫu nhiên đều trong [−4, 0] rồi đặt α = 10<sup>r</sup>', ['Lấy α ngẫu nhiên đều trong [0.0001, 1]', 'Lấy α = 10<sup>−4</sup> × r với r đều trong [0, 1]', 'Chỉ thử hai giá trị 10<sup>−4</sup> và 1'],
  'Lấy đều trên thang tuyến tính sẽ dồn khoảng 90% mẫu vào [0.1, 1]. Lấy mẫu trên thang log chia đều cho mỗi bậc độ lớn (10<sup>−4</sup>…10<sup>−3</sup>, 10<sup>−3</sup>…10<sup>−2</sup>, …).'),
Q('dlai-improve', 'Lúc suy luận (test) với từng ảnh riêng lẻ, lớp Batch Normalization dùng trung bình và phương sai nào?',
  'Ước lượng trung bình trượt của μ và σ² tích lũy trong quá trình huấn luyện', ['Trung bình và phương sai của chính ảnh đang suy luận', 'Luôn dùng μ = 0 và σ² = 1', 'Trung bình và phương sai của batch test đầu tiên'],
  'Khi suy luận có thể chỉ có một mẫu nên không tính được thống kê batch. BatchNorm lưu running_mean và running_var (trung bình trượt mũ) trong lúc huấn luyện và dùng chúng khi ở chế độ eval.'),
Q('dlai-improve', 'Khi đặt Batch Normalization ngay sau một lớp tuyến tính z = Wx + b, vì sao có thể bỏ tham số bias b?',
  'Vì bước trừ trung bình của BatchNorm triệt tiêu b, và tham số β của BatchNorm đảm nhận vai trò dịch chuyển', ['Vì BatchNorm không làm việc được với bias', 'Vì bias làm gradient biến mất', 'Vì bias chỉ cần cho lớp đầu ra'],
  'BatchNorm tính (z − μ)/σ. Cộng hằng số b vào mọi phần tử thì μ cũng tăng đúng b, nên b bị triệt tiêu. Sau đó γ·ẑ + β cung cấp lại phép co giãn và dịch chuyển, nên b là thừa.'),
Q('cs231n', 'Trước khi huấn luyện trên toàn bộ dữ liệu, CS231n khuyên làm một bước kiểm tra nhanh nào để phát hiện lỗi cài đặt?',
  'Cho mô hình học trên một tập rất nhỏ (ví dụ 20 mẫu) và kiểm tra nó có đạt mất mát gần 0 không', ['Huấn luyện ngay với learning rate lớn nhất có thể', 'Tắt toàn bộ chính quy hóa và huấn luyện 100 epoch trên toàn bộ dữ liệu', 'Chỉ kiểm tra độ chính xác trên tập test'],
  'Một mô hình cài đặt đúng phải học thuộc được vài mẫu. Nếu không overfit nổi tập nhỏ thì nhiều khả năng có lỗi trong dữ liệu, hàm mất mát hoặc vòng lặp huấn luyện. Đây là bước "sanity check" trong phần babysitting the learning process.'),
Q('cs231n', 'Một bộ phân loại softmax 10 lớp được khởi tạo với trọng số rất nhỏ. Giá trị mất mát cross-entropy ban đầu hợp lý nhất là bao nhiêu?',
  ['≈ 0', '≈ 1', '≈ 2.30', '≈ 10'], fix=2,
  exp='Trọng số nhỏ làm mọi lớp có xác suất gần bằng nhau, 1/10. Mất mát = −ln(1/10) = ln 10 ≈ 2.30. Nếu mất mát ban đầu khác xa giá trị này thì có thể đã cài đặt sai.'),

# --- Structuring ML Projects ---
Q('dlai-struct', 'Một bộ phân loại có precision 0.9 và recall 0.6. Điểm F1 của nó là bao nhiêu?',
  ['0.60', '0.72', '0.75', '0.80'], fix=1,
  exp='F1 = 2PR / (P + R) = 2 × 0.9 × 0.6 / 1.5 = 1.08 / 1.5 = 0.72. F1 là trung bình điều hòa nên bị kéo về giá trị nhỏ hơn.'),
Q('dlai-struct', 'Yêu cầu sản phẩm: tối đa hóa độ chính xác với điều kiện thời gian chạy không quá 100 ms. Nên chọn bộ phân loại nào?' + table([['Bộ phân loại', 'Độ chính xác', 'Thời gian chạy'], ['P', '90%', '80 ms'], ['Q', '92%', '95 ms'], ['R', '95%', '1500 ms'], ['S', '88%', '20 ms']]),
  ['P', 'Q', 'R', 'S'], fix=1,
  exp='Thời gian chạy là chỉ số thỏa mãn (satisficing): chỉ cần ≤ 100 ms. Độ chính xác là chỉ số tối ưu (optimizing). Trong các bộ đạt điều kiện (P, Q, S), Q có độ chính xác cao nhất. R chính xác nhất nhưng vi phạm điều kiện thời gian.'),
Q('dlai-struct', 'Nguyên tắc nào đúng khi chọn tập dev và tập test?',
  'Hai tập nên đến từ cùng một phân phối, phản ánh dữ liệu mà mô hình sẽ gặp trong thực tế', ['Tập dev nên lấy từ dữ liệu dễ hơn tập test', 'Tập test nên giống hệt tập huấn luyện', 'Tập dev và test nên lấy từ hai quốc gia khác nhau để đa dạng'],
  'Tập dev là "mục tiêu" nhóm tối ưu theo. Nếu dev và test khác phân phối, mô hình tốt trên dev chưa chắc tốt trên test và công sức tối ưu bị lãng phí.'),
Q('dlai-struct', 'Với bộ dữ liệu khoảng 1 triệu mẫu trong thời kỳ deep learning, cách chia nào hợp lý?',
  '98% huấn luyện, 1% dev, 1% test', ['60% huấn luyện, 20% dev, 20% test', '50% huấn luyện, 50% test', '10% huấn luyện, 45% dev, 45% test'],
  'Khi dữ liệu rất lớn, 1% (10.000 mẫu) đã đủ để đánh giá tin cậy. Dồn phần lớn cho huấn luyện có lợi hơn. Tỉ lệ 60/20/20 phù hợp với dữ liệu nhỏ, vài nghìn mẫu.'),
Q('dlai-struct', 'Phân tích lỗi (error analysis) theo cách khuyên dùng gồm bước nào?',
  'Lấy khoảng 100 mẫu dev bị dự đoán sai, xem thủ công và đếm tỉ lệ từng loại lỗi', ['Huấn luyện lại mô hình với seed khác', 'Xóa toàn bộ mẫu bị sai khỏi tập dev', 'Chỉ nhìn vào đường cong mất mát'],
  'Đếm tỉ lệ các nhóm lỗi (ảnh mờ, nhãn sai, chó bị nhận nhầm là mèo…) cho biết mức cải thiện tối đa nếu sửa từng nhóm, nhờ đó ưu tiên đúng việc cần làm.'),
Q('dlai-struct', 'Dữ liệu huấn luyện là ảnh từ web, còn tập dev là ảnh chụp từ điện thoại người dùng. Kết quả: sai số train 1%, train-dev 1.5%, dev 10%. Vấn đề chính là gì?',
  'Lệch phân phối dữ liệu (data mismatch)', ['Phương sai cao', 'Độ lệch cao', 'Tập dev quá lớn'],
  'Tập train-dev cùng phân phối với tập huấn luyện nhưng mô hình chưa thấy. Sai số train-dev gần bằng train (1.5% so với 1%) nên phương sai không lớn. Bước nhảy từ 1.5% lên 10% đến từ khác biệt giữa ảnh web và ảnh điện thoại.'),
Q('dlai-struct', 'Sai số của con người là 0.5%, sai số huấn luyện 5%, sai số dev 6%. Nên tập trung vào điều gì?',
  'Giảm độ lệch tránh được (avoidable bias)', ['Giảm phương sai', 'Thu thập thêm dữ liệu dev', 'Mô hình đã đạt mức con người, không cần cải thiện'],
  'Avoidable bias = 5% − 0.5% = 4.5%, còn phương sai = 6% − 5% = 1%. Độ lệch lớn hơn nhiều nên cần mô hình mạnh hơn, huấn luyện lâu hơn hoặc tối ưu tốt hơn.'),
Q('dlai-struct', 'Khi nào học đầu-cuối (end-to-end deep learning) thường không phải là lựa chọn tốt?',
  'Khi dữ liệu có nhãn cho toàn bộ bài toán từ đầu vào đến đầu ra còn ít', ['Khi có rất nhiều dữ liệu (x, y) cho toàn bộ bài toán', 'Khi muốn bớt thiết kế đặc trưng thủ công', 'Khi bài toán là nhận dạng giọng nói với hàng chục nghìn giờ dữ liệu'],
  'End-to-end cần lượng lớn cặp (đầu vào, đầu ra cuối). Khi dữ liệu ít, chia bài toán thành các bước nhỏ (ví dụ phát hiện khuôn mặt rồi mới nhận dạng), mỗi bước có nhiều dữ liệu riêng, thường hiệu quả hơn.'),

# --- CNN và transfer learning (CS231n, d2l, PyTorch tutorial) ---
Q('cs231n', 'Đầu vào kích thước 63 × 63 × 16 đi qua lớp tích chập có 32 bộ lọc 7 × 7, stride 2, không padding. Kích thước đầu ra là bao nhiêu?',
  ['28 × 28 × 32', '29 × 29 × 32', '29 × 29 × 16', '57 × 57 × 32'], fix=1,
  exp='Kích thước không gian = ⌊(63 − 7)/2⌋ + 1 = 28 + 1 = 29. Số kênh đầu ra bằng số bộ lọc, 32. Kết quả: 29 × 29 × 32.'),
Q('cs231n', 'Một lớp tích chập có 10 bộ lọc kích thước 5 × 5, nhận đầu vào 3 kênh, mỗi bộ lọc có một bias. Lớp có bao nhiêu tham số?',
  ['750', '760', '250', '780'], fix=1,
  exp='Mỗi bộ lọc có 5 × 5 × 3 = 75 trọng số cộng 1 bias, tức 76 tham số. Với 10 bộ lọc: 76 × 10 = 760. Số tham số không phụ thuộc kích thước ảnh đầu vào.'),
Q('cs231n', 'Với kernel 7 × 7 và stride 1, cần padding bao nhiêu ở mỗi phía để kích thước đầu ra bằng đầu vào ("same")?',
  ['1', '2', '3', '7'], fix=2,
  exp='Để giữ nguyên kích thước với stride 1: p = (k − 1)/2 = (7 − 1)/2 = 3.'),
Q('cs231n', 'Lớp max pooling 2 × 2, stride 2 có bao nhiêu tham số học được?',
  ['0', '4', '1', '2'], fix=0,
  exp='Pooling chỉ áp phép toán cố định (lấy max hoặc trung bình) nên không có tham số học. Kích thước cửa sổ và stride là siêu tham số.'),
Q('cs231n', 'Xếp chồng ba lớp tích chập 3 × 3 (stride 1) có vùng tiếp nhận (receptive field) bằng một lớp 7 × 7. Lợi ích của cách xếp chồng là gì?',
  'Ít tham số hơn và có thêm phi tuyến giữa các lớp', ['Nhiều tham số hơn nên biểu diễn mạnh hơn', 'Không cần hàm kích hoạt', 'Đầu ra có độ phân giải cao hơn'],
  'Với C kênh vào và ra, ba lớp 3 × 3 cần 3 × 9C² = 27C² tham số, còn một lớp 7 × 7 cần 49C². Ngoài ra có ba lần ReLU thay vì một nên mạng biểu diễn được hàm phức tạp hơn. Đây là ý tưởng của VGG.'),
Q('d2l', 'Tác dụng chính của tích chập 1 × 1 trong các mạng như GoogLeNet hay ResNet là gì?',
  'Thay đổi số kênh (ví dụ giảm số kênh) với chi phí tính toán thấp', ['Phát hiện cạnh theo phương ngang', 'Tăng kích thước không gian của ảnh', 'Thay thế hoàn toàn lớp pooling'],
  'Tích chập 1 × 1 là một lớp fully connected áp tại từng điểm ảnh, trộn thông tin giữa các kênh. Nó thường dùng làm "bottleneck" giảm số kênh trước tích chập 3 × 3 hoặc 5 × 5 đắt tiền.'),
Q('cs231n', 'So với lớp fully connected, lợi thế lớn nhất về số tham số của lớp tích chập đến từ đâu?',
  'Chia sẻ tham số: cùng một bộ lọc được dùng ở mọi vị trí, và mỗi đầu ra chỉ nối với một vùng nhỏ', ['Lớp tích chập không có bias', 'Lớp tích chập luôn dùng stride lớn', 'Lớp tích chập chỉ xử lý ảnh xám'],
  'Một bộ lọc 3 × 3 trượt trên toàn ảnh dùng chung 9 trọng số (nhân số kênh) cho mọi vị trí. Kết hợp với kết nối cục bộ, số tham số giảm hàng nghìn lần so với nối đầy đủ.'),
Q('d2l', 'Tính chất "đồng biến với phép tịnh tiến" (translation equivariance) của lớp tích chập nghĩa là gì?',
  'Dịch chuyển ảnh đầu vào thì bản đồ đặc trưng đầu ra dịch chuyển tương ứng', ['Đầu ra hoàn toàn không đổi khi ảnh bị xoay', 'Đầu ra không đổi khi ảnh bị phóng to', 'Mạng cho kết quả giống nhau với mọi ảnh'],
  'Vì cùng bộ lọc được áp ở mọi vị trí, một mẫu hình xuất hiện ở đâu thì phản hồi mạnh xuất hiện ở đó. Tịnh tiến đầu vào làm đầu ra tịnh tiến theo. Pooling bổ sung thêm một phần tính bất biến cục bộ.'),
Q('pt-tl', 'Trong tutorial transfer learning của PyTorch, phép biến đổi dữ liệu nào chỉ nên áp cho tập huấn luyện mà không áp cho tập validation?',
  'RandomResizedCrop và RandomHorizontalFlip', ['ToTensor', 'Normalize với mean/std của ImageNet', 'Resize và CenterCrop'],
  'Các phép ngẫu nhiên là augmentation, chỉ dùng khi huấn luyện để tăng đa dạng dữ liệu. Tập validation cần biến đổi tất định (Resize, CenterCrop, ToTensor, Normalize) để kết quả đánh giá ổn định.'),
Q('pt-tl', 'Ở cách "ConvNet as fixed feature extractor" trong tutorial PyTorch, những tham số nào được tối ưu?',
  'Chỉ tham số của lớp fully connected cuối mới thay vào', ['Toàn bộ tham số của mạng', 'Chỉ các lớp tích chập đầu tiên', 'Không có tham số nào được tối ưu'],
  'Ta đặt requires_grad = False cho toàn bộ mạng pretrained rồi thay lớp fc bằng lớp mới (mặc định requires_grad = True). Optimizer chỉ nhận model.fc.parameters(). Huấn luyện nhanh vì không cần gradient cho phần lớn mạng.'),
Q('pt-tl', 'Muốn dùng ResNet-18 pretrained cho bài toán 2 lớp, dòng lệnh nào thay đúng lớp phân loại cuối?',
  '<code>model.fc = nn.Linear(model.fc.in_features, 2)</code>', ['<code>model.fc = nn.Linear(2, model.fc.out_features)</code>', '<code>model.conv1 = nn.Conv2d(2, 64, 7)</code>', '<code>model.avgpool = nn.Linear(512, 2)</code>'],
  'Lớp fc của ResNet-18 nhận vector 512 chiều (in_features) và xuất 1000 lớp ImageNet. Ta giữ in_features và đổi số đầu ra thành 2.'),
Q('pt-tl', 'Gọi <code>model.eval()</code> trong PyTorch có tác dụng gì?',
  'Chuyển các lớp như Dropout và BatchNorm sang chế độ suy luận', ['Tắt việc tính gradient', 'Đóng băng mọi trọng số vĩnh viễn', 'Chuyển mô hình sang GPU'],
  'eval() chỉ đổi hành vi của các lớp phụ thuộc chế độ: Dropout không tắt nơ-ron, BatchNorm dùng running statistics. Nó không tắt autograd; muốn tiết kiệm bộ nhớ khi suy luận cần thêm torch.no_grad().'),
Q('pt-tl', 'Khi chạy suy luận trong PyTorch, vì sao nên bọc mã trong <code>with torch.no_grad():</code>?',
  'Để không lưu đồ thị tính toán phục vụ backward, giảm bộ nhớ và tăng tốc', ['Để tắt Dropout', 'Để chuẩn hóa đầu vào', 'Để tự động chuyển tensor sang CPU'],
  'Khi suy luận không cần gradient. no_grad() ngăn autograd ghi lại các phép toán nên tiết kiệm bộ nhớ và nhanh hơn. Thường dùng cùng model.eval().'),
Q('pt-tl', 'Khi dùng mô hình pretrained trên ImageNet, vì sao phải chuẩn hóa ảnh với mean [0.485, 0.456, 0.406] và std [0.229, 0.224, 0.225]?',
  'Để đầu vào có cùng phân phối với dữ liệu mô hình đã được huấn luyện', ['Để ảnh chuyển sang thang xám', 'Để tăng độ phân giải ảnh', 'Vì PyTorch bắt buộc mọi mô hình dùng giá trị này'],
  'Đây là trung bình và độ lệch chuẩn theo từng kênh RGB của ImageNet. Trọng số pretrained đã quen với đầu vào được chuẩn hóa như vậy; đổi cách chuẩn hóa làm đặc trưng bị lệch và giảm độ chính xác.'),
Q('d2l', 'Khi fine-tune mô hình pretrained, chiến lược learning rate nào thường được khuyên dùng?',
  'Learning rate nhỏ cho các lớp pretrained, learning rate lớn hơn cho lớp đầu ra mới', ['Learning rate lớn cho mọi lớp để học nhanh', 'Learning rate bằng 0 cho lớp đầu ra mới', 'Learning rate lớn cho lớp pretrained, nhỏ cho lớp mới'],
  'Các lớp pretrained đã có trọng số tốt nên chỉ cần chỉnh nhẹ. Lớp đầu ra khởi tạo ngẫu nhiên cần học từ đầu nên dùng learning rate lớn hơn (d2l dùng gấp 10 lần).'),
Q('d2l', 'Áp global average pooling lên bản đồ đặc trưng kích thước 7 × 7 × 512 cho đầu ra kích thước bao nhiêu?',
  ['512', '7 × 7', '25088', '49'], fix=0,
  exp='Global average pooling lấy trung bình mỗi kênh trên toàn bộ 7 × 7 vị trí, nên mỗi kênh còn một số và thu được vector 512 chiều. Flatten trực tiếp thì sẽ được 7 × 7 × 512 = 25088.'),
Q('d2l', 'Trong khối residual của ResNet, khi số kênh của nhánh chính khác số kênh của đầu vào x thì làm thế nào để cộng được?',
  'Đưa x qua tích chập 1 × 1 (có thể với stride) để khớp kích thước trước khi cộng', ['Bỏ kết nối tắt ở khối đó', 'Nhân x với 0', 'Cộng x vào sau lớp fully connected cuối'],
  'Phép cộng F(x) + x yêu cầu cùng shape. Khi số kênh hoặc kích thước không gian thay đổi, ResNet dùng nhánh chiếu (projection shortcut) là tích chập 1 × 1 để khớp shape.'),
Q('d2l', 'Trong khối Inception của GoogLeNet, đầu ra của các nhánh (1 × 1, 3 × 3, 5 × 5, pooling) được kết hợp thế nào?',
  'Nối (concatenate) theo chiều kênh', ['Cộng phần tử', 'Nhân phần tử', 'Lấy nhánh có giá trị lớn nhất'],
  'Các nhánh giữ cùng kích thước không gian nhờ padding, rồi được nối theo chiều kênh. Mạng tự học cách kết hợp đặc trưng ở nhiều kích thước vùng tiếp nhận.'),
Q('d2l', 'Vì sao Batch Normalization hoạt động kém khi batch size rất nhỏ (ví dụ 2)?',
  'Trung bình và phương sai ước lượng trên batch quá nhiễu', ['Vì BatchNorm cần batch size là lũy thừa của 10', 'Vì GPU không hỗ trợ batch nhỏ', 'Vì BatchNorm chỉ hoạt động với ảnh xám'],
  'Với vài mẫu, thống kê batch dao động mạnh nên quá trình chuẩn hóa không ổn định. Các phương pháp như Layer Norm hay Group Norm chuẩn hóa trong từng mẫu nên không phụ thuộc batch size.'),
Q('d2l', 'Tích chập depthwise separable (như trong MobileNet) với 64 kênh vào, 64 kênh ra, kernel 3 × 3 cần bao nhiêu trọng số (bỏ qua bias)? Tích chập thường cần 36 864.',
  ['576', '4 096', '4 672', '36 864'], fix=2,
  exp='Depthwise: mỗi kênh một bộ lọc 3 × 3, tức 3 × 3 × 64 = 576. Pointwise 1 × 1 trộn kênh: 64 × 64 = 4 096. Tổng 4 672, ít hơn khoảng 8 lần so với tích chập thường (3 × 3 × 64 × 64 = 36 864).'),

# --- Học máy cổ điển (scikit-learn User Guide) ---
Q('sklearn', 'Tham số <code>stratify=y</code> trong <code>train_test_split</code> có tác dụng gì?',
  'Giữ tỉ lệ các lớp trong tập train và test giống với dữ liệu gốc', ['Xáo trộn dữ liệu theo thời gian', 'Loại bỏ các lớp hiếm', 'Chuẩn hóa nhãn y về [0, 1]'],
  'Phân tầng (stratified split) đặc biệt quan trọng với dữ liệu mất cân bằng: nếu không, tập test có thể thiếu hẳn lớp hiếm.'),
Q('sklearn', 'Cách dùng <code>StandardScaler</code> nào đúng để tránh rò rỉ dữ liệu?',
  'fit trên tập huấn luyện, rồi transform cả tập huấn luyện và tập test', ['fit trên toàn bộ dữ liệu rồi mới chia train/test', 'fit riêng trên tập test', 'fit_transform trên tập test, transform trên tập train'],
  'Thống kê chuẩn hóa (μ, σ) chỉ được học từ dữ liệu huấn luyện. Dùng thông tin của tập test khi fit là rò rỉ dữ liệu, làm điểm đánh giá đẹp hơn thực tế.'),
Q('sklearn', 'Lợi ích chính của <code>Pipeline</code> trong scikit-learn khi kết hợp với cross-validation là gì?',
  'Các bước tiền xử lý được fit lại trên từng fold huấn luyện, tránh rò rỉ dữ liệu sang fold kiểm tra', ['Làm mô hình chạy trên GPU', 'Tự động chọn thuật toán tốt nhất', 'Tăng số lượng dữ liệu huấn luyện'],
  'Nếu chuẩn hóa toàn bộ dữ liệu trước rồi mới cross-validation, fold kiểm tra đã "góp mặt" vào thống kê chuẩn hóa. Pipeline đóng gói tiền xử lý và mô hình thành một estimator nên mỗi fold được xử lý đúng.'),
Q('sklearn', 'Với <code>cross_val_score(model, X, y, cv=5)</code>, quá trình diễn ra thế nào?',
  'Dữ liệu chia thành 5 phần, mỗi phần lần lượt làm tập kiểm tra một lần, mô hình được huấn luyện 5 lần', ['Mô hình được huấn luyện 1 lần và đánh giá 5 lần trên cùng tập test', 'Dữ liệu được nhân bản 5 lần', 'Chỉ dùng 1/5 dữ liệu để huấn luyện'],
  'K-fold cross-validation trả về K điểm số, mỗi điểm ứng với một fold làm tập kiểm tra và K − 1 fold còn lại làm tập huấn luyện. Trung bình các điểm cho ước lượng hiệu suất ổn định hơn.'),
Q('sklearn', 'Sau khi chạy <code>GridSearchCV</code>, thuộc tính nào chứa bộ siêu tham số tốt nhất?',
  '<code>best_params_</code>', ['<code>coef_</code>', '<code>feature_importances_</code>', '<code>classes_</code>'],
  'best_params_ là dict siêu tham số cho điểm cross-validation cao nhất, best_score_ là điểm đó, best_estimator_ là mô hình đã fit lại trên toàn bộ dữ liệu với bộ tốt nhất (khi refit=True).'),
Q('sklearn', 'Một bộ phân loại có TP = 40, FP = 10, FN = 20. Precision và recall lần lượt là bao nhiêu?',
  ['0.8 và 0.667', '0.667 và 0.8', '0.8 và 0.8', '0.5 và 0.667'], fix=0,
  exp='Precision = TP/(TP + FP) = 40/50 = 0.8. Recall = TP/(TP + FN) = 40/60 ≈ 0.667.'),
Q('sklearn', 'ROC AUC bằng 0.5 nói lên điều gì về bộ phân loại nhị phân?',
  'Khả năng xếp hạng không tốt hơn đoán ngẫu nhiên', ['Bộ phân loại hoàn hảo', 'Bộ phân loại luôn đoán sai', 'Độ chính xác đúng bằng 50%'],
  'AUC là xác suất một mẫu dương ngẫu nhiên được chấm điểm cao hơn một mẫu âm ngẫu nhiên. 0.5 tương đương tung đồng xu, 1.0 là hoàn hảo. AUC không đồng nghĩa với accuracy.'),
Q('sklearn', 'Ma trận nhầm lẫn của một bộ phân loại nhị phân có TN = 50, FP = 10, FN = 5, TP = 35. Độ chính xác (accuracy) là bao nhiêu?',
  ['78%', '80%', '85%', '87.5%'], fix=2,
  exp='Accuracy = (TP + TN)/tổng = (35 + 50)/100 = 85%.'),
Q('sklearn', 'Khác biệt giữa macro-average và micro-average khi tính F1 cho bài toán nhiều lớp là gì?',
  'Macro tính F1 từng lớp rồi lấy trung bình đều; micro gộp TP, FP, FN của mọi lớp rồi mới tính', ['Macro chỉ dùng cho bài toán nhị phân', 'Micro bỏ qua lớp hiếm hoàn toàn', 'Hai cách luôn cho cùng kết quả'],
  'Macro coi mọi lớp quan trọng như nhau nên phản ánh tốt hiệu suất trên lớp hiếm. Micro bị lớp đông mẫu chi phối; với phân loại đơn nhãn, micro-F1 bằng accuracy.'),
Q('sklearn', 'Trong <code>LogisticRegression</code> của scikit-learn, giảm tham số C có tác dụng gì?',
  'Tăng mức chính quy hóa', ['Giảm mức chính quy hóa', 'Tăng số vòng lặp tối đa', 'Đổi sang hồi quy tuyến tính'],
  'C là nghịch đảo của cường độ chính quy hóa (C = 1/λ). C nhỏ phạt trọng số mạnh hơn, mô hình đơn giản hơn.'),
Q('sklearn', 'Với SVM kernel RBF, khi tăng gamma rất lớn thì mô hình có xu hướng gì?',
  'Mỗi điểm huấn luyện chỉ ảnh hưởng một vùng rất nhỏ, biên quyết định phức tạp và dễ overfit', ['Biên quyết định gần như tuyến tính', 'Mô hình bỏ qua toàn bộ support vector', 'Mô hình luôn underfit'],
  'gamma quyết định bán kính ảnh hưởng của mỗi mẫu: K(x, x′) = exp(−γ‖x − x′‖²). γ lớn khiến kernel giảm rất nhanh nên biên quyết định bám sát từng điểm. γ nhỏ cho biên mượt, gần tuyến tính.'),
Q('sklearn', 'Trong SVM soft-margin, tăng tham số C có tác dụng gì?',
  'Phạt nặng hơn các điểm vi phạm lề, lề hẹp lại và mô hình bám dữ liệu huấn luyện hơn', ['Lề rộng hơn và chấp nhận nhiều lỗi hơn', 'Loại bỏ hẳn các support vector', 'Chuyển kernel từ RBF sang tuyến tính'],
  'C cân bằng giữa lề rộng và số lỗi huấn luyện. C lớn ưu tiên phân loại đúng mọi điểm (lề hẹp, dễ overfit); C nhỏ cho lề rộng, chấp nhận vài lỗi (chính quy hóa mạnh hơn).'),
Q('sklearn', 'Một nút của cây quyết định chứa 3 mẫu lớp X và 1 mẫu lớp Y. Chỉ số Gini của nút là bao nhiêu?',
  ['0.250', '0.375', '0.500', '0.811'], fix=1,
  exp='Gini = 1 − Σp² = 1 − (0.75² + 0.25²) = 1 − (0.5625 + 0.0625) = 0.375. Giá trị 0.811 là entropy của cùng nút.'),
Q('sklearn', 'Nút cha có 4 mẫu dương và 4 mẫu âm (entropy = 1). Một phép tách chia thành hai nút con (3 dương, 1 âm) và (1 dương, 3 âm). Information gain gần đúng bằng bao nhiêu?',
  ['0.189', '0.311', '0.500', '0.811'], fix=0,
  exp='Mỗi nút con có entropy H(0.75, 0.25) = −0.75·log₂0.75 − 0.25·log₂0.25 ≈ 0.811. Hai nút con có cùng kích thước nên entropy có trọng số là 0.811. IG = 1 − 0.811 ≈ 0.189.'),
Q('sklearn', 'Trong Random Forest, việc chỉ xét một tập con ngẫu nhiên các đặc trưng ở mỗi lần tách (max_features) nhằm mục đích gì?',
  'Giảm tương quan giữa các cây để việc lấy trung bình giảm phương sai hiệu quả hơn', ['Làm mỗi cây chính xác hơn', 'Giảm số cây cần dùng xuống còn một', 'Biến Random Forest thành thuật toán boosting'],
  'Nếu một đặc trưng rất mạnh, mọi cây đều tách theo nó và trở nên giống nhau. Lấy trung bình các cây tương quan mạnh giảm phương sai rất ít. Chọn ngẫu nhiên đặc trưng làm các cây khác nhau hơn.'),
Q('sklearn', 'Gradient Boosting xây dựng tập hợp cây theo cách nào?',
  'Tuần tự: mỗi cây mới học phần sai số (gradient âm của hàm mất mát) mà các cây trước để lại', ['Song song và độc lập trên các mẫu bootstrap', 'Một cây duy nhất rất sâu', 'Ngẫu nhiên hóa toàn bộ ngưỡng tách'],
  'Boosting cộng dần các mô hình yếu, mỗi mô hình sửa lỗi của tổng hiện tại. Bagging/Random Forest thì huấn luyện các cây độc lập rồi lấy trung bình.'),
Q('sklearn', 'Khi dùng phương pháp "khuỷu tay" (elbow) để chọn K cho K-means, ta vẽ đại lượng nào theo K?',
  'Inertia: tổng bình phương khoảng cách từ mỗi điểm tới tâm cụm của nó', ['Độ chính xác phân loại', 'Số vòng lặp đến khi hội tụ', 'Số điểm ngoại lai'],
  'Inertia luôn giảm khi K tăng. Ta chọn K tại điểm "khuỷu", nơi tăng K thêm chỉ giảm inertia rất ít. Trong scikit-learn giá trị này là thuộc tính inertia_.'),
Q('sklearn', 'Mục đích của khởi tạo k-means++ là gì?',
  'Chọn các tâm ban đầu nằm xa nhau, giúp hội tụ nhanh hơn và ít rơi vào nghiệm kém', ['Tự động chọn số cụm K', 'Bảo đảm tìm được cực tiểu toàn cục', 'Cho phép K-means dùng dữ liệu có nhãn'],
  'k-means++ chọn tâm đầu tiên ngẫu nhiên, các tâm tiếp theo được chọn với xác suất tỉ lệ với bình phương khoảng cách tới tâm gần nhất đã chọn. Nó không bảo đảm nghiệm tối ưu toàn cục, nên scikit-learn vẫn chạy nhiều lần (n_init).'),
Q('sklearn', 'Phát biểu nào đúng về thuật toán DBSCAN?',
  'Tìm được cụm có hình dạng bất kỳ và gán nhãn −1 cho điểm nhiễu', ['Cần biết trước số cụm K', 'Chỉ tìm được cụm hình cầu', 'Mọi điểm đều bắt buộc thuộc một cụm'],
  'DBSCAN dựa trên mật độ với hai tham số eps (bán kính lân cận) và min_samples. Cụm là vùng điểm dày đặc nối với nhau; điểm không thuộc vùng dày nào là nhiễu với nhãn −1.'),
Q('sklearn', 'Trong phân cụm phân cấp gộp (AgglomerativeClustering), kiểu liên kết "ward" gộp hai cụm theo tiêu chí nào?',
  'Gộp cặp cụm làm tổng phương sai trong cụm tăng ít nhất', ['Gộp cặp cụm có hai điểm gần nhau nhất', 'Gộp cặp cụm có hai điểm xa nhau nhất', 'Gộp ngẫu nhiên'],
  'Ward tối thiểu hóa mức tăng tổng bình phương sai số trong cụm, tương tự mục tiêu của K-means. Liên kết "single" dùng cặp điểm gần nhất, "complete" dùng cặp điểm xa nhất.'),
Q('sklearn', 'Câu lệnh <code>PCA(n_components=0.95)</code> trong scikit-learn có nghĩa là gì?',
  'Giữ số thành phần chính tối thiểu sao cho tổng phương sai được giải thích đạt ít nhất 95%', ['Giữ đúng 95 thành phần chính', 'Loại 95% số đặc trưng', 'Chỉ dùng 95% số mẫu'],
  'Khi n_components là số thực trong (0, 1), PCA tự chọn số thành phần dựa trên explained_variance_ratio_ tích lũy.'),
Q('sklearn', 'Một điểm có khoảng cách trung bình tới các điểm cùng cụm a = 0.2 và tới cụm gần nhất khác b = 0.5. Hệ số silhouette của điểm là bao nhiêu?',
  ['0.3', '0.4', '0.6', '2.5'], fix=2,
  exp='s = (b − a) / max(a, b) = (0.5 − 0.2)/0.5 = 0.6. Silhouette nằm trong [−1, 1]; gần 1 nghĩa là điểm nằm gọn trong cụm của nó.'),
Q('sklearn', 'Giả định cốt lõi của bộ phân loại Naive Bayes là gì?',
  'Các đặc trưng độc lập có điều kiện với nhau khi đã biết lớp', ['Các đặc trưng có phân phối đều', 'Các lớp có cùng số mẫu', 'Dữ liệu phân tách tuyến tính được'],
  'Nhờ giả định này, P(x|y) = Π P(x<sub>i</sub>|y), nên mô hình rất đơn giản và nhanh. Giả định hiếm khi đúng hoàn toàn nhưng mô hình vẫn hoạt động tốt, ví dụ khi phân loại văn bản.'),
Q('sklearn', 'Nghiệm dạng đóng (phương trình chuẩn) của hồi quy tuyến tính bình phương tối thiểu là gì?',
  'θ = (XᵀX)<sup>−1</sup>Xᵀy', ['θ = XᵀX y', 'θ = (XXᵀ)<sup>−1</sup>y', 'θ = X<sup>−1</sup>yᵀ'],
  'Đặt gradient của ‖Xθ − y‖² bằng 0 được XᵀXθ = Xᵀy, suy ra θ = (XᵀX)<sup>−1</sup>Xᵀy khi XᵀX khả nghịch. Ridge thêm λI: θ = (XᵀX + λI)<sup>−1</sup>Xᵀy.'),
Q('sklearn', 'Phát biểu nào đúng về hệ số R² (<code>r2_score</code>) trong scikit-learn?',
  'R² = 1 là dự đoán hoàn hảo, và R² có thể âm nếu mô hình tệ hơn việc luôn dự đoán giá trị trung bình', ['R² luôn nằm trong [0, 1]', 'R² = 0 là dự đoán hoàn hảo', 'R² chỉ dùng cho bài toán phân loại'],
  'R² = 1 − SS<sub>res</sub>/SS<sub>tot</sub>. Dự đoán hằng số bằng trung bình cho R² = 0; mô hình sai lệch hơn thế cho R² âm.'),

# --- NLP và LLM (CS224n, Hugging Face Course) ---
Q('cs224n', 'Mục tiêu huấn luyện của mô hình Word2Vec skip-gram là gì?',
  'Dùng từ trung tâm để dự đoán các từ trong cửa sổ ngữ cảnh xung quanh', ['Dùng các từ xung quanh để dự đoán từ trung tâm', 'Dự đoán câu tiếp theo', 'Phân loại cảm xúc của câu'],
  'Skip-gram tối đa hóa P(từ ngữ cảnh | từ trung tâm). CBOW làm ngược lại: dự đoán từ trung tâm từ các từ ngữ cảnh.'),
Q('cs224n', 'Phép tính vector nào minh họa khả năng biểu diễn quan hệ ngữ nghĩa của word embedding?',
  'vec("king") − vec("man") + vec("woman") ≈ vec("queen")', ['vec("king") × vec("queen") = 1', 'vec("king") + vec("queen") = 0', 'vec("man") = vec("woman")'],
  'Các quan hệ như giới tính hay thủ đô–quốc gia thường ứng với các hướng gần như cố định trong không gian embedding, nên phép tương tự (analogy) được giải bằng cộng trừ vector rồi tìm từ gần nhất theo cosine.'),
Q('hf', 'Vì sao các tokenizer hiện đại như WordPiece hay BPE dùng đơn vị từ con (subword)?',
  'Để xử lý được từ hiếm hoặc chưa gặp bằng cách tách thành các mảnh đã có trong từ vựng, mà từ vựng vẫn có kích thước vừa phải', ['Để mỗi ký tự là một token riêng', 'Để bỏ qua dấu câu', 'Để mọi câu có cùng số token'],
  'Tokenizer theo từ cần từ vựng khổng lồ và vẫn gặp từ ngoài từ vựng (OOV). Tokenizer theo ký tự tạo chuỗi rất dài. Subword cân bằng hai điều này: từ phổ biến giữ nguyên, từ hiếm được tách, ví dụ "tokenization" → "token", "##ization".'),
Q('hf', 'Trong thư viện Transformers, cách nhanh nhất để chạy phân tích cảm xúc với mô hình mặc định là gì?',
  '<code>pipeline("sentiment-analysis")</code>', ['<code>AutoModel.train("sentiment")</code>', '<code>Tokenizer.sentiment()</code>', '<code>datasets.load("sentiment-analysis")</code>'],
  'pipeline() gói ba bước tiền xử lý (tokenizer), chạy mô hình và hậu xử lý thành một lệnh. Lần đầu nó tải về checkpoint mặc định cho tác vụ.'),
Q('hf', 'Vì sao nên tải tokenizer bằng <code>AutoTokenizer.from_pretrained</code> với đúng tên checkpoint của mô hình?',
  'Mô hình chỉ hiểu đúng các ID token được tạo bởi cùng từ vựng và quy tắc tách từ lúc nó được huấn luyện', ['Vì tokenizer khác nhau cho cùng kết quả', 'Để tokenizer chạy được trên GPU', 'Vì AutoTokenizer tự huấn luyện lại tokenizer'],
  'Mỗi ID ứng với một hàng trong ma trận embedding của mô hình. Dùng tokenizer khác làm ID trỏ sai hàng, mô hình nhận đầu vào vô nghĩa.'),
Q('hf', 'Khi mã hóa một batch câu có độ dài khác nhau bằng tokenizer của Hugging Face, cần các tham số nào để tạo tensor hình chữ nhật?',
  '<code>padding=True</code> và <code>truncation=True</code>', ['<code>lowercase=True</code> và <code>strip=True</code>', '<code>shuffle=True</code>', '<code>return_dict=False</code>'],
  'Padding thêm token đệm vào câu ngắn cho bằng câu dài nhất, truncation cắt câu vượt quá độ dài tối đa của mô hình. attention_mask đánh dấu token đệm để mô hình bỏ qua chúng.'),
Q('hf', 'Trong BERT, token đặc biệt [CLS] và [SEP] có vai trò gì?',
  '[CLS] đặt ở đầu chuỗi, biểu diễn của nó thường dùng cho phân loại; [SEP] ngăn cách các câu và đánh dấu kết thúc', ['[CLS] đánh dấu từ bị che, [SEP] đánh dấu từ viết hoa', 'Cả hai là token đệm', '[CLS] dùng cho dịch máy, [SEP] dùng cho tóm tắt'],
  'Với cặp câu, đầu vào có dạng [CLS] câu A [SEP] câu B [SEP]. Token bị che khi pretraining là [MASK], còn token đệm là [PAD].'),
Q('hf', 'Mục tiêu pretraining chính của BERT là gì?',
  'Dự đoán các token bị che (masked language modeling), cùng với dự đoán câu tiếp theo trong bản gốc', ['Dự đoán token tiếp theo từ trái sang phải', 'Dịch câu sang ngôn ngữ khác', 'Phân loại ảnh'],
  'BERT che ngẫu nhiên khoảng 15% token và dự đoán chúng dựa vào ngữ cảnh cả hai phía, nhờ đó học được biểu diễn hai chiều. Next Sentence Prediction là mục tiêu phụ trong bản BERT gốc.'),
Q('hf', 'Kiến trúc của các mô hình họ GPT là gì?',
  'Chỉ gồm decoder, attention bị che để mỗi token chỉ nhìn các token phía trước', ['Chỉ gồm encoder, attention hai chiều', 'Encoder-decoder như T5', 'Mạng hồi quy LSTM'],
  'GPT là mô hình ngôn ngữ tự hồi quy (auto-regressive), sinh văn bản từng token một. Mặt nạ nhân quả (causal mask) ngăn token nhìn thấy tương lai.'),
Q('hf', 'Loại mô hình nào phù hợp nhất với tác vụ tóm tắt văn bản hoặc dịch máy?',
  'Mô hình encoder-decoder (sequence-to-sequence) như T5 hoặc BART', ['Mô hình chỉ encoder như BERT', 'Mô hình phân loại ảnh', 'Mô hình K-means'],
  'Encoder đọc toàn bộ câu nguồn, decoder sinh câu đích dựa trên biểu diễn đó. Encoder-only hợp với phân loại hoặc gán nhãn token; decoder-only hợp với sinh văn bản tự do.'),
Q('cs224n', 'Trong scaled dot-product attention, vì sao chia QKᵀ cho √d<sub>k</sub>?',
  'Để tích vô hướng không quá lớn khi d<sub>k</sub> lớn, tránh softmax bão hòa và gradient rất nhỏ', ['Để đầu ra luôn nằm trong [0, 1]', 'Để giảm số tham số', 'Để biến attention thành tuyến tính'],
  'Nếu các phần tử của q và k có phương sai 1, tích vô hướng có phương sai d<sub>k</sub>. Giá trị lớn đẩy softmax về one-hot, làm gradient gần 0. Chia √d<sub>k</sub> đưa phương sai về khoảng 1.'),
Q('cs224n', 'Lợi ích của multi-head attention so với một head duy nhất là gì?',
  'Mỗi head có thể chú ý tới các kiểu quan hệ khác nhau trong các không gian con biểu diễn khác nhau', ['Giảm độ phức tạp xuống tuyến tính theo độ dài chuỗi', 'Loại bỏ nhu cầu positional encoding', 'Thay thế lớp feed-forward'],
  'Mỗi head có ma trận chiếu Q, K, V riêng. Các head có thể học quan hệ cú pháp, đồng tham chiếu, vị trí gần… rồi được nối lại và chiếu ra.'),
Q('cs224n', 'Vì sao Transformer cần thêm positional encoding vào embedding của token?',
  'Vì self-attention không phân biệt thứ tự: hoán vị các token chỉ làm hoán vị đầu ra', ['Để giảm kích thước từ vựng', 'Để thay cho attention mask', 'Vì embedding không chứa nghĩa của từ'],
  'Self-attention tính trên tập token như một tập hợp. Không có thông tin vị trí thì "chó cắn người" và "người cắn chó" cho cùng biểu diễn. Positional encoding (sin/cos hoặc học được) bổ sung thứ tự.'),
Q('cs224n', 'Vì sao RNN thuần khó học các phụ thuộc xa trong chuỗi dài, và LSTM giải quyết điều đó thế nào?',
  'Gradient bị nhân lặp qua nhiều bước thời gian nên biến mất; LSTM dùng ô nhớ và các cổng để thông tin, gradient truyền đi xa', ['RNN không có tham số chia sẻ; LSTM thêm chia sẻ tham số', 'RNN chỉ xử lý được ảnh', 'RNN không dùng hàm kích hoạt'],
  'Backprop through time nhân nhiều lần với cùng ma trận trọng số và đạo hàm hàm kích hoạt, nên gradient co lại theo cấp số. Trạng thái ô nhớ của LSTM được cập nhật chủ yếu bằng phép cộng có cổng điều khiển, nên gradient ít bị suy giảm.'),
Q('cs224n', 'Mô hình ngôn ngữ có cross-entropy trung bình 2 nat/token trên tập test. Perplexity xấp xỉ bao nhiêu?',
  ['2', '4', '7.39', '100'], fix=2,
  exp='Perplexity = exp(cross-entropy) = e² ≈ 7.39. Có thể hiểu mô hình phân vân như đang chọn đều giữa khoảng 7.4 token ở mỗi bước. Nếu cross-entropy tính bằng bit thì perplexity là 2 mũ giá trị đó.'),
Q('hf', 'Khi sinh văn bản, tăng tham số temperature (ví dụ từ 0.7 lên 1.5) gây ra điều gì?',
  'Phân phối xác suất phẳng hơn nên văn bản đa dạng, ngẫu nhiên hơn và dễ lạc đề', ['Văn bản luôn giống hệt nhau giữa các lần sinh', 'Mô hình sinh nhanh gấp đôi', 'Mô hình chỉ chọn token có xác suất cao nhất'],
  'Logit được chia cho temperature trước softmax. T &gt; 1 làm phân phối phẳng hơn; T &lt; 1 làm phân phối nhọn hơn; T → 0 gần với greedy decoding.'),
Q('hf', 'Kỹ thuật RAG (Retrieval-Augmented Generation) giúp gì cho mô hình ngôn ngữ lớn?',
  'Truy xuất tài liệu liên quan và đưa vào prompt để câu trả lời dựa trên nguồn, giảm bịa đặt và cập nhật được kiến thức mới', ['Tăng số tham số của mô hình', 'Huấn luyện lại toàn bộ mô hình mỗi khi có tài liệu mới', 'Nén mô hình để chạy trên điện thoại'],
  'RAG gồm bước truy xuất (thường bằng tìm kiếm vector embedding) và bước sinh có điều kiện trên đoạn văn tìm được. Không cần fine-tune khi kho tài liệu thay đổi.'),

# --- Thị giác máy tính nâng cao (IOAI syllabus, CS231n) ---
Q('ioai', 'Tính IoU giữa hai hộp có tọa độ (x<sub>1</sub>, y<sub>1</sub>, x<sub>2</sub>, y<sub>2</sub>) là (0, 0, 4, 4) và (2, 2, 6, 6).',
  ['0.143', '0.250', '0.333', '0.500'], fix=0,
  exp='Vùng giao từ (2, 2) đến (4, 4), diện tích 2 × 2 = 4. Mỗi hộp có diện tích 16. Hợp = 16 + 16 − 4 = 28. IoU = 4/28 ≈ 0.143.'),
Q('ioai', 'Chỉ số mAP (mean Average Precision) trong phát hiện vật thể được tính thế nào?',
  'Tính Average Precision (diện tích dưới đường precision–recall) cho từng lớp ở một ngưỡng IoU, rồi lấy trung bình các lớp', ['Lấy trung bình IoU của mọi hộp dự đoán', 'Lấy accuracy trên toàn bộ ảnh', 'Đếm số hộp dự đoán đúng chia cho số ảnh'],
  'Một dự đoán được coi là đúng khi IoU với hộp thật vượt ngưỡng (ví dụ 0.5). AP tổng hợp precision ở các mức recall. COCO còn lấy trung bình mAP qua nhiều ngưỡng IoU từ 0.5 đến 0.95.'),
Q('cs231n', 'Khác biệt chính giữa bộ phát hiện một giai đoạn (như YOLO, SSD) và hai giai đoạn (như Faster R-CNN) là gì?',
  'Hai giai đoạn sinh vùng đề xuất (region proposals) trước rồi mới phân loại và tinh chỉnh; một giai đoạn dự đoán hộp và lớp trực tiếp trong một lần chạy', ['Một giai đoạn luôn chính xác hơn', 'Hai giai đoạn không dùng CNN', 'Một giai đoạn chỉ phát hiện được một vật thể mỗi ảnh'],
  'Faster R-CNN dùng mạng đề xuất vùng (RPN) rồi phân loại từng vùng, thường chính xác hơn nhưng chậm hơn. YOLO và SSD dự đoán dày đặc trên lưới hoặc anchor nên nhanh, phù hợp thời gian thực.'),
Q('ioai', 'Khác biệt giữa phân đoạn ngữ nghĩa (semantic segmentation) và phân đoạn thực thể (instance segmentation) là gì?',
  'Phân đoạn ngữ nghĩa gán lớp cho từng pixel; phân đoạn thực thể còn tách riêng từng đối tượng của cùng một lớp', ['Hai khái niệm là một', 'Phân đoạn ngữ nghĩa chỉ vẽ hộp bao', 'Phân đoạn thực thể không gán lớp'],
  'Trong ảnh có ba người, phân đoạn ngữ nghĩa tô mọi pixel người cùng một nhãn "người". Phân đoạn thực thể (như Mask R-CNN) cho ba mặt nạ riêng: người 1, người 2, người 3.'),
Q('ioai', 'Mặt nạ dự đoán A có 40 pixel, mặt nạ thật B có 50 pixel, phần giao có 30 pixel. Hệ số Dice bằng bao nhiêu?',
  ['0.500', '0.600', '0.667', '0.750'], fix=2,
  exp='Dice = 2|A ∩ B| / (|A| + |B|) = 2 × 30 / (40 + 50) = 60/90 ≈ 0.667. Dice loss = 1 − Dice.'),

# --- Mô hình sinh và học tự giám sát (IOAI syllabus) ---
Q('ioai', 'Hàm mất mát của Variational Autoencoder (VAE) gồm hai thành phần nào?',
  'Sai số tái tạo và độ phân kỳ KL giữa phân phối ẩn q(z|x) và phân phối tiên nghiệm p(z)', ['Mất mát đối kháng và mất mát chu trình', 'Cross-entropy phân loại và L1 trên trọng số', 'Chỉ sai số tái tạo'],
  'Sai số tái tạo buộc giải mã ra ảnh giống đầu vào. Số hạng KL kéo phân phối ẩn về gần N(0, I) để không gian ẩn liên tục, từ đó lấy mẫu sinh dữ liệu mới được.'),
Q('ioai', 'Quá trình "thuận" (forward process) của mô hình khuếch tán (diffusion model) là gì?',
  'Thêm dần nhiễu Gaussian vào dữ liệu qua nhiều bước cho đến khi gần như là nhiễu thuần', ['Nén ảnh thành vector ẩn bằng encoder', 'Cho generator và discriminator đối kháng', 'Sinh ảnh từ nhiễu trong một bước'],
  'Quá trình thuận cố định, không cần học. Mô hình học quá trình ngược: dự đoán nhiễu đã thêm ở từng bước để khử nhiễu dần, nhờ đó sinh ảnh mới từ nhiễu ngẫu nhiên.'),
Q('ioai', 'Trong huấn luyện GAN, bộ phân biệt (discriminator) được tối ưu để làm gì?',
  'Phân biệt đúng mẫu thật từ dữ liệu với mẫu giả do generator tạo ra', ['Sinh ảnh có độ phân giải cao', 'Nén ảnh thành vector ẩn', 'Tái tạo ảnh đầu vào'],
  'Discriminator là bộ phân loại nhị phân thật/giả. Generator được tối ưu để đánh lừa discriminator. Hai mạng chơi trò chơi minimax.'),
Q('ioai', 'Hiện tượng "mode collapse" trong GAN là gì?',
  'Generator chỉ sinh ra một vài kiểu mẫu rất giống nhau, bỏ qua sự đa dạng của dữ liệu thật', ['Discriminator không còn tham số', 'Ảnh sinh ra có độ phân giải quá cao', 'Mất mát của generator luôn bằng 0'],
  'Generator tìm được vài mẫu đánh lừa được discriminator nên cứ sinh lặp lại chúng. Ví dụ huấn luyện trên chữ số 0–9 mà chỉ sinh ra chữ số 1.'),
Q('ioai', 'Trong SimCLR, cặp mẫu dương (positive pair) được tạo ra thế nào, và vì sao batch lớn có lợi?',
  'Hai phép tăng cường khác nhau của cùng một ảnh; batch lớn cung cấp nhiều mẫu âm hơn cho contrastive loss', ['Hai ảnh khác nhau cùng nhãn; batch lớn giảm bộ nhớ', 'Một ảnh và nhãn của nó; batch lớn làm mô hình nhỏ hơn', 'Hai ảnh ngẫu nhiên bất kỳ; batch lớn không có tác dụng'],
  'SimCLR không dùng nhãn. Mỗi ảnh tạo hai view bằng crop, đổi màu, làm mờ… Hai view đó là cặp dương; các view của mọi ảnh khác trong batch là mẫu âm. Nhiều mẫu âm hơn giúp biểu diễn học được tốt hơn.'),
]
